@startuml Components
!theme plain
title Smart Home — Device Service — Components
!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Person(Customer, "Customer")
Container(APIGW, "API GateWay")
Container_Boundary(DeviceService, "Device Service") {
	Component(API, "API")
	Component(CommandProcessor, "Command Processor")
	Component(StateManager, "StateManager")
	Component(Rerository, "Rerository")
	Component(Consumer, "Telemetry Consumer")
	Component(Producer, "Telemetry Producer")
}
ContainerDb(DeviceDB, "Device DB")
ContainerQueue(DataBus, "Data Bus", "Kafka")
System_Ext(UserDevices, "User's Devices")

Rel(Customer, APIGW, "Send request")
Rel(APIGW, API, "Manage Device")
Rel(API, CommandProcessor, "")
Rel(API, StateManager, "")
Rel(CommandProcessor, Rerository, "Save command")
Rel(StateManager, Rerository, "Get state")
Rel(Rerository, DeviceDB, "Save and receive data")
Rel(Consumer, CommandProcessor, "Call command")
Rel(CommandProcessor, Producer, "Send command")
Rel(Producer, DataBus, "Produce command")
Rel(DataBus, Consumer, "Receive sensor data")
BiRel(DataBus, UserDevices, "Send sensor data and receive commands for devices")
@enduml